### PR TITLE
Set kilt$isWrapped to true when wrapping a porting lib fluid type.

### LINKED ISSUE #736: Mecanism x Create
### Version information

Kilt-20.1.14

### Reproduction Steps

1 .launch game
2. creating a world in creative
3. opening the inventory
4. typing in the search bar "tank" or "fluid" game crashes

Image

### Java Provider + Version

I don't know

### Crash Report file

-

### Log file

https://gist.github.com/Stimer223/2e070dfbb18b936d3ec4c1d3c9e7580a

### Additional information

When I run Mekanism and Create together, my game crashes, but not right away.How can I fix this?
I am using Kilt to make Mekanism work on Fabric
Mekanism-1.20.1-10.4.16.80
create-fabric-6.0.8.1+build.1744-mc1.20.1

### PR DESCRIPTION
**Pull request by Acuadragon100**
Closes KiltMC/Kilt#736

### CODE REVIEW

**Comment by BluSpring** [comment]
that.. fix was so much easier than i thought it would be

File: src/main/java/net/minecraftforge/fluids/FluidType.java [hunk 1]
```diff
@@ -126,6 +126,7 @@ private FluidType(io.github.fabricators_of_create.porting_lib.fluids.FluidType w
         );
 
         this.kilt$wrapped = wrapped;
+        this.kilt$isWrapped = true;
```
Comment (asoji) [inline src/main/java/net/minecraftforge/fluids/FluidType.java:129]: no shot that it was this fucking easy LMAO
